modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/Alex-the-666/" #optional
[[mods]] #mandatory
modId="astro" #mandatory
version="1.0.0" #mandatory
displayName="Astronautical" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods" #optional
#logoFile="rats_logo.png" #optional
authors="Alexthe666" #optional
description='''Blast Off!'''
[[dependencies.astro]] #optional
    # the modid of the dependency
    modId="citadel" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[1.4.0,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="AFTER"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"